# Gradle 配置
org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
org.gradle.parallel=true

# Kotlin 配置
kotlin.code.style=official
kotlin.stdlib.default.dependency=false

# IntelliJ Platform 配置
pluginGroup=com.github.easygit
pluginName=EasyGit
pluginVersion=1.0.6

# 目标 IDE 版本
platformType=IC
platformVersion=2023.3

# 支持的 IDE 版本范围
pluginSinceBuild=233
pluginUntilBuild=253.*
